version: '3.8'

services:
  vprodb:
    image: horlar/vprofiledb:V1
    container_name: db01 
    build:
      context: ./Docker-files/db
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin123

  vprocache01:
    image: memcached
    container_name: mc01
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq:latest
    container_name: rmq01
    restart: always
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest


  vproapp:
    image: horlar/vprofileapp:V1
    container_name: vproapp 
    build:
      context: ./Docker-files/app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

  vproweb:
    image: horlar/vprofileweb:V1 
    container_name: vproweb 
    build:
      context: ./Docker-files/web
      dockerfile: Dockerfile
    ports:
      - "80:80"


volumes:
  vprodbdata: {}
  vproappdata: {}