services:
  jenkins:
    image: myjenkins/blueocean:2.387.3
    user: root
    container_name: jenkins
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    networks:
      - cicd-networks
    restart: on-failure
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    depends_on:
      - docker

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    restart: unless-stopped
    ports:
      - 9000:9000
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
      - sonarqube-extentions:/opt/sonarqube/extensions
    networks:
      - cicd-networks

  docker:
    image: docker:dind
    container_name: docker
    ports:
      - 2376:2376
      - 8888:8888
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    networks:
      - cicd-networks
    privileged: true
    restart: always
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home

networks:
  cicd-networks:
    driver: bridge

volumes:
  jenkins-docker-certs:
  jenkins-data:
  sonarqube-data:
  sonarqube-logs:
  sonarqube-extentions: